version: '3'
services:
  json-server:
    build: .
    ports:
      - '3000:3000'
    command: npm run json-server

  vite-app:
    build: ./client
    ports:
      - '5173:5173'
    command: npm run dev
    volumes:
      - ./client:/app
      - /app/node_modules
