version: '3'
services:
  json-server:
    build:
      dockerfile_inline: |
        FROM node:18
        WORKDIR /app
        RUN npm install -g json-server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/
    command: npx json-server --watch db.json

  vite-app:
    build: .
    ports:
      - '5173:5173'
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
